### ISSUE TITLE
Missing SyncPromise.all()?

### ISSUE THREAD

**Issue by cambiata** [DenkiYagi/hxgnd#1]
Hi, and thank you for this library! Seems to be what I've been looking for..! :-)

One thing that I'm missing, though - the equivalent of Promise.all():
```
        var p1 = js.Promise.resolve(123);
        var p2 = js.Promise.resolve(345);
        js.Promise.all([p1, p2])
            .then(function(values){
               trace(values); 
            });
```
Any plans for implementing that?

**Comment by terurou** [comment]
Hi, @cambiata. Thanks your good issue!
I enhanced Promise API. Please try the newest commits!

# Added Promise
`hxgnd.Promise` is the async Promise.
`hxgnd.Promise` can be treated as `js.Promise` and is same `js.Promise` on JavaScript target.

```js
var p: js.Promise = hxgnd.Promise.resolve(1);
```

# Enhanced SyncPromise
`hxgnd.SyncPromise` is changed that can be treated as `js.Promise`.

```js
var p1: js.Promise = hxgnd.SyncPromise.resolve(1);
var p2: hxgnd.Promise = hxgnd.SyncPromise.resolve(2);
```

# Added Promise.all() and Promise.race()
```js
hxgnd.Promise.all([
    js.Promise.resolve(1),
    hxgnd.Promise.resolve(2),
    hxgnd.SyncPromise.resolve(3),
]).then(function (values) {
    trace(values);
});
```

**Comment by cambiata** [comment]
Wow, thanks! Will have a look!
